### ISSUE TITLE
RBF applied to Cube with a hole

### ISSUE THREAD

**Issue by DavideBaroliUniLu** [mathLab/PyGeM#102]
I try to use PyGeM with this demo:

[demoRBF1.txt](https://github.com/mathLab/PyGeM/files/601382/demoRBF1.txt)

The result shows that both the cube  and hole  are deformed, but  the control points are only on the surface of the hole. So the cube should not change his shape. Are there some modifications to add in the src part?

**Comment by mtezzele** [comment]
I haven't seen yet the file but RBF is interpolatory on the control points. If you want the cube preserved I suggest you to collocate control points also on that surface. Let me know if this fix the problem. For more technicalities please consult the paper referred in the documentation of the RBF class.
