### ISSUE TITLE
Prescribed deformation

### ISSUE THREAD

**Issue by benoitpaillard** [mathLab/PyGeM#107]
Hi all, and thanks for this very promising tool.

I'm wondering wether PyGeM would be able to deform a 3D mesh, based on the prescribed motion of a body. That would be interesting in loosely coupled FSI problems, where the body is deformed by a structural solver, and this deformed body then needs to be simulated with a fluid domain again.

Similarly for ship study it would enable one to deform a mesh based on the calculated attitude... Many applications !

Thanks for your reply.

Benoit Paillard

**Comment by mtezzele** [comment]
Dear Benoit,
up to now pygem deforms your mesh using FFD or RBF only. If you are interested in developing such a feature contact me by mail so we can figure out the best way to do it.

**Comment by benoitpaillard** [comment]
Ok thanks ! The thing is I have absolutely zero idea of how to do that... I
know there are a couple of implementation for OpenFOAM, which we might want
to look at. What are your thoughts ?

Thanks again.

2017-03-27 16:38 GMT+02:00 Marco Tezzele <notifications@github.com>:
