### ISSUE TITLE
Problems with complex geometric models (multiple faces and shells) 

### ISSUE THREAD

**Issue by zjiang0529** [mathLab/PyGeM#109]
Hello Mr. Salmoiraghi and Mr. Tezzele, 

We would like to thank you for providing this useful tool PyGeM. 
In the context of our application, we intend to use several PyGeM functionalities for the geometric modelling of organs. However, we have encountered some problems because the processing involves complex geometries imported from CAD files (iges or step), which contain, for example, shells composed of multiple faces. These problems include:

- importing multiple geometric entities (shells, faces etc.)
- linking multiple geometric entities (linking edges into a single wire, trimming the surface with the wire, linking multiple surfaces to a single shell etc.)
- surface repairing before exporting to a CAD file (iges or step)

Based on the source code implemented in PyGeM, we have applied some modification to fix these issues. Hence, we would like to propose and work on improvements on such features, which will enable the package to process more complex geometries. The following classes and functions will be concerned by the improvement of input/output functionalities:

- In class **Nurbshandler**: _parse()_ and _write()_
- In class **Igeshandler**: _load_shape_from_file()_
- In class **Stephandler**: _load_shape_from_file()_

Sincerely,
Zhifan JIANG

**Comment by mtezzele** [comment]
Hi! We are very interested in such features. As we spoke about by email I think the best way to proceed is to start a pull request ;)

Best,
Marco

**Comment by zjiang0529** [comment]
Hello! We are actually working on it. We will ask for a pull request once we have checked the commits. 

Sincerely,
Zhifan
