### ISSUE TITLE
tl;dr installation 

### ISSUE THREAD

**Issue by rahulvigneswaran** [mathLab/PyGeM#166]
I would like to add a conda `.yml` environment file for easy hassle-free installation of the dependencies and tl;dr installation procedure in the documentation for beginners who just want to use PyGeM instantly.

**Comment by ndem0** [comment]
@rahulvigneswaran The installation procedure is not that complex at the moment, you just need to get the right version of python-occ, so the README is sufficient. Anyway, feel free to add the `.yml` file to a new pull request, we will evaluate its usefulness.

**Comment by rahulvigneswaran** [comment]
I made a `.yml` file of the conda environment and tried to replicate the environment in a virtual machine. The `pip` packages are causing errors. So the currently stated method seems to be the best as of now.

Thank you @ndem0 .
