### ISSUE TITLE
Dockerfile out of date on DockerHub

### ISSUE THREAD

**Issue by jak1502** [mathLab/PyGeM#180]
Hi,

I can see the docker file has been updated but it hasn't been pushed to docker - it still has the older version of python.

https://hub.docker.com/r/pygemdocker/pygem/dockerfile

Thanks
Jack

**Comment by ndem0** [comment]
I built the new image, so now you should see the latest version even on Docker.
The repository address is changed: [https://hub.docker.com/r/sissamathlab/pygem](https://hub.docker.com/r/sissamathlab/pygem).

I leave the issue open, just in case there will be other problems related with the image.
Thanks for reporting!
