### ISSUE TITLE
fails to run testsuite with V2.0 on Debian/Testing

### ISSUE THREAD

**Issue by Trophime** [mathLab/PyGeM#209]
Hi,
I'm experiencing some troubles while running test for V2.0 release.
It seems that the cad python files are not installed and it leads to a lot of errors...

Is this behaviour normal? (or shall the files be installed?)
If this is normal why not removing tests involving importing modules from cad?
Moreover, it seems to me that files in cad do not reflect names of modules (except on system which are case insensitive)...

**Comment by ndem0** [comment]
Hi @Trophime, have you read the dependencies guide in the README page?
Which error do you get running the tests?

Finally, I really do not understand your sentence:
> Moreover, it seems to me that files in cad do not reflect names of modules (except on system which are case insensitive)...

**Comment by Trophime** [comment]
Hi, 
actually I'm trying to package PyGem V2.0 for Debian after successfully packaged pythonocc-core.
I attached the log of the package building.

As there is no affine.py, nor some params.py I removed the corresponding test in test_package.py
You will note that I have add pygem/cad files into .pybuild directory before running tests
Moreover if I change pygem/cad/nubrshandler.py to pygem/cad/NurbsHandler.py and other files likewise.
That's what I mean in my last remark.

**Comment by ndem0** [comment]
I still meet some difficulties to understand your problem. Please, try to provide all information we are asking (try to copy directly from terminal)

> actually I'm trying to package PyGem V2.0 for Debian after successfully packaged pythonocc-core.
> I attached the log of the package building.
What do you mean with "trying to package"? Where did you attach the log? Also, which log? Can you explain also how did you install PyGeM? Which version of `pythonocc` have you installed? Which operating system?

> As there is no affine.py, nor some params.py I removed the corresponding test in test_package.py
> You will note that I have add pygem/cad files into .pybuild directory before running tests
How do you run the tests? From the README: To run tests locally (the package nose is required): `python test.py`.
How actually am I supposed to see changes into `.pybuild` directory?

> Moreover if I change pygem/cad/nubrshandler.py to pygem/cad/NurbsHandler.py and other files likewise.
Sorry, but the sentence seems to not have a sense to me.

Additionally, what is the real errors you get running the tests? Copy the shell input and output.

**Comment by Trophime** [comment]
Here is the log:
[pygem_2.0-1_amd64.log](https://github.com/mathLab/PyGeM/files/5231687/pygem_2.0-1_amd64.log)

What I'm trying to do is make a debian package for PyGem. See https://wiki.debian.org/Python/LibraryStyleGuide

**Comment by ndem0** [comment]
Too many information is missing to tackle properly the problem. 
Also, I really do not understand the reason of pushing that effort to convert an already built package (that also is independent from the operating system thanks to `pip`) to have an identical package installable only on Deb systems.

Try to follow the README page for installation and testing phases. If you have some problems, open an issue being sure to put: the exact line you digit into the shell and ALL the error you get. Use formatted text please.

**Comment by Trophime** [comment]
If I may, I prefer using deb packages instead of pip install to keep my machines clean.
I don't want to mix several installation method.
That's why I'm trying to build PyGem as a package just like I've done it with pythonocc-core with success.

**Comment by ndem0** [comment]
Your machine, your choice!
But we are developing the Python package and we've not plan to support also other package managers.
