### ISSUE TITLE
Power parameter not properly accounted for in RBF interpolation

### ISSUE THREAD

**Issue by andreamola** [mathLab/PyGeM#225]
There seems to be a problem with the second parameter (power) in most of the RBF kernel functions. Apparently, it is ignored.
I have a python scpt and a parameter file to reproduce the issue, if needed.

**Comment by andreamola** [comment]
Ok, so to summarize things here, we found one mistake on my part and one tiny bug.
First, I was mistakenly under the impression that power was still an attribute of the RBF class, but since 2.0 version it is not the case. I got misled by its presence in some parameter files in the test section.
Second, there indeed is a small bug consisting in a commented line (rbf.py:395) that must be uncommented to properly pass additional parameters to the RBFFactory functions.
I will go ahead with a PR to fix that line and purge some occurrence of the power parameter in the parameter files around the library.

**Comment by ndem0** [comment]
fix in #226 and #228
