### ISSUE TITLE
Problem in reading stl from exemple 5

### ISSUE THREAD

**Issue by Lyshtar** [mathLab/PyGeM#238]
Hello, i am currently interesting in using stl files, i tryed exemple 5 but when i run it i got an error with
stl_content = io.STLHandler.read(stl_filename)

telling that :
  File "/home/lcalmett/Documents/untitled0.py", line 67, in <module>
    stl_content = io.STLHandler.read(stl_filename)

  File "/home/lcalmett/anaconda3/envs/py37/lib/python3.7/site-packages/smithers-0.0.1-py3.7.egg/smithers/io/stlhandler.py", line 32, in read
    result['points'] = cls._vtk_to_numpy_(data.GetPoints().GetData())

AttributeError: 'NoneType' object has no attribute 'GetData'

the exemple 5 work perfetly for VTP files but not STL,
Do you have an idea to solve this issue?
Best regards,
Lucie

**Comment by ndem0** [comment]
Dear @Lyshtar,
It is not totally clear to me if you are running the tutorial or a modified version of the latter.
I've just tried again the STL deformation and the points seem to be correctly extracted by the STL. Have you try to visualize the `cube.stl` file you downloaded, e.g. using Paraview?

**Comment by Lyshtar** [comment]
Hello, i tried to run the tutorial and got the previous error:
"
File "/home/lcalmett/anaconda3/envs/py37/lib/python3.7/site-packages/smithers-0.0.1-py3.7.egg/smithers/io/stlhandler.py", line 32, in read
result['points'] = cls.vtk_to_numpy(data.GetPoints().GetData())

AttributeError: 'NoneType' object has no attribute 'GetData'
"
Yes, i tried to visualize it with paraview i get no problem

**Comment by ndem0** [comment]
We have checked again the tutorial, on different computer and different environments, and no errors occur. 
Are you sure the STL file is not corrupted? Both the `STLHandler` and `VTPHandler` are based on the same library, the `vtk` module for Python.
Have you tried to run the Smithers tests regarding the `STLHandler`? BTW I guess is a problem of the handler, not directly connected to PyGeM

**Comment by Lyshtar** [comment]
Thank you for your answer i've tried to run the smithers test, it work perfectly for vtp files but i have exactly the same mistake for stl file, maybe my problem is with the vtk module, i've read that some of people got mistakes with this module.
I've tried different STL file, so i guess its not a corruption problem

**Comment by Lyshtar** [comment]
Hello, i've find a solution to make it work, in my STL description I need to replace all the . by ,
For exemple the STL format is normally:
solid ascii
 facet normal -1 0 0
  outer loop
   vertex -0.5 -0.5 -0.5
   vertex -0.5 -0.5 0.5
   vertex -0.5 0.5 -0.5
  endloop
 endfacet
....
and i change it by :
solid ascii
 facet normal -1 0 0
  outer loop
   vertex -0,5 -0,5 -0,5
   vertex -0,5 -0,5 0,5
   vertex -0,5 0,5 -0,5
  endloop
 endfacet
....

Sadly paraview can't read it, i need to reconvert, this is a strange error, i guess it's from vtk, i have no clue on how to change it, do you think it's possible?
