### ISSUE TITLE
No module named sphinx_rtd_theme

### ISSUE THREAD

**Issue by tpaviot** [mathLab/PyGeM#94]
Building sphinx documentation on Windows/py27:

```
>cd docs
>make html
Running Sphinx v1.4.6

Exception occurred:
  File "conf.py", line 20, in <module>
ImportError: No module named sphinx_rtd_theme
```

**Comment by mtezzele** [comment]
We didn't test the package on windows. I thought that adding 'sphinx_rtd_theme' in the install_requires of the setup.py would have be sufficient. Let me know if it doesn't install the module sphinx_rtd_theme using the command setup.py install. Maybe it has to be installed separately.

**Comment by smnuman** [comment]
Not only in Windows, I got it in my MBA 11". The full error I got is as follows:
```

$ :make html
mkdir -p build/html build/doctrees
sphinx-build -b html -d build/doctrees -D latex_paper_size=  . build/html 
Running Sphinx v1.5.3

Exception occurred:
  File "conf.py", line 113, in <module>
    import sphinx_rtd_theme
ImportError: No module named sphinx_rtd_theme
The full traceback has been saved in /var/folders/8k/xyg7mlln417g33n9rjxpqwjc0000gn/T/sphinx-err-CYSnST.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [build] Error 1


```

What is it's solution or a way out? Any idea?

**Comment by mtezzele** [comment]
@smnuman did you install the package through 

`python setup.py install` ?

It should install the package sphinx_rtd_theme. If not please install it separately with

`pip install sphinx_rtd_theme`

Moreover you can find the documentation online at [this site](http://mathlab.github.io/PyGeM/).
Let me know if it solves the problem.

**Comment by smnuman** [comment]
@mtezzele Yes I had to install it seperately after your suggestion with : 
`pip install sphinx_rtd_theme`

Thanks

**Comment by banderlog** [comment]
In my case I missed a coma in `conf.py` file:

```diff
extensions = [
-    'sphinx_rtd_theme'
    'sphinx.ext.autodoc',
    'sphinx_autodoc_typehints'
]


extensions = [
+    'sphinx_rtd_theme',
    'sphinx.ext.autodoc',
    'sphinx_autodoc_typehints'
]
```
