### ISSUE TITLE
Nose is required for testing

### ISSUE THREAD

**Issue by tpaviot** [mathLab/PyGeM#95]
The nose testing framework is a required dependency for testing, but it's not documented:

```
>Miniconda2\python test.py
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    import nose
ImportError: No module named nose
```

**Comment by mtezzele** [comment]
I think it is related with #94.

**Comment by mtezzele** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github https://github.com/mathLab/PyGeM/issues/95](https://trello.com/c/AIO4DuUk/8-github-https-github-com-mathlab-pygem-issues-95)

**Comment by ndem0** [comment]
Add the missing dependencies in 745f8063f1e62ff2963c6d4aef3c103a12385646.
